plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.aoe.canbusmonitor'
    compileSdk 36

    defaultConfig {
        applicationId "com.aoe.canbusmonitor.turnsound"
        minSdk 33
        targetSdk 33
        versionCode 14
        versionName "1.6.4-performance-pass"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(path: ':fytcanbusmonitor')
    testImplementation 'junit:junit:4.13.2'
}
